language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable
  sonarcloud:
    organization: "donkeykongjr-github"
  
before_install: cd src/pimlify-vue

script:
  - npm test
  - sonar-scanner

before_deploy:
  - npm run build

deploy:
  skip_cleanup: true
  provider: firebase
  token: ${FIREBASE_API_TOKEN}