language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable
  sonarcloud:
    organization: "donkeykongjr-github"
  
before_install: cd src/pimlify-vue

script:
  - npm run build
  - sonar-scanner

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "OuIa+wtyOGXhAXqLlqpjPBH3VDpo0WeQlbo6lg6uybLofXo9OjxE5DUkMr605ac8KOJrAiSAQGdJWVT2OJzT7emLchqWjWdOSDa5i5wxuf0M5JtueT7BdTkOm8tN+QI0d4PqfmSpApF//MoJEbu65A3qQxeG80NsmXr3bOqoCrLhVc9qdLxBbfY2g1+UOO6sf5nzsS9rwj5LYwoIwkwN3V0d60Bf3sVt/oKwtDHHV0Apr0VaBcZ/S2nzUQeKBOZ8d6fFCg0rnI66thtKlFm+KB0owYz+Oai0V46OjQybXsFfDH5rrYbgYcHK7cirVTzxACjtFJZpBf0GIw9y075llkL/iqgwYQNTZxAntj8OcWL9w+IeIIPF3YjGFTLk4kQaEvApUS+iN7qjceSgbuTwxBmrIW56vk13dAM+Z3V3GQCriRfwTklQJfiiFefUh/IwHoUgOgizSw0slE0aW5MvXZgloNAeqPQdicPnM/rC/gxB+2C+58pgkJaOGRTDF416TIZjBk4rpVSQHwTQxoUQVrBE8jEk3Kfi7BaBH3hxyYPTNLzT4UmFT4qoelXHxQMLyesg3msw5xZFFqEdJOV6ptkilKWTNc4WFOSjjQcCZNn7y6kJ11rPlC2Nzr0suCM6gA5lgAqSR5Dcw4Qw8U5ODSGO1b2gRM82SI3EWXoBgTc="
