language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

branches:
  only:
  - master

addons:
  chrome: stable
  sonarcloud:
    organization: "donkeykongjr-github"
  
before_install: cd src/pimlify-vue

script:
  - npm run build
  - sonar-scanner
  - firebase deploy --token=${FIREBASE_API_TOKEN}
